### ISSUE TITLE
Error: There was an issue sorting changed files from Github

### ISSUE THREAD

**Issue by cboulanger** [trilom/file-changes-action#100]
**Describe the bug**
I am getting this error:

```
Run trilom/file-changes-action@v1.2.3
  with:
    githubToken: ***
    output: json
    fileOutput: json
(node:2491) UnhandledPromiseRejectionWarning: Error: {"error":"500/TypeError","from":"sortChangedFiles","message":"There was an issue sorting files changed.","payload":"{}"}
    at run (/home/runner/work/_actions/trilom/file-changes-action/v1.2.3/dist/index.js:1:19989)
```
See https://github.com/qooxdoo/documentation/runs/731107827#step:3:1

**Workflow**
See https://github.com/qooxdoo/documentation/actions/runs/122603076/workflow

**Comment by aszenz** [comment]
We are seeing the same issue with PR's that have file renames

**Comment by trilom** [comment]
Hey guys, sorry for the delay on this it slipped my notifications!

Please take a look at the version and try to use v1.2.4 or master.  Part of my CI was/is _supposed_ to change the version in the readme but isn’t functioning.

For completeness, after a release is done on a release branch it is merged to the master so master will always be current with latest release so it’s safe.

**Comment by yo1995** [comment]
@trilom Thanks for this clarification! Would you also update the `v1.2.3` in README to reflect this change?
