### ISSUE TITLE
`output` doesn't work with single space strings

### ISSUE THREAD

**Issue by dorner** [trilom/file-changes-action#81]
**Describe the bug**
When using the `output` parameter with an empty string, the files are concatenated together without any separator.

**Workflow**
```
    - name: Get file changes
      id: get_file_changes
      uses: trilom/file-changes-action@v1.2.0
      with:
        githubToken: ${{ secrets.GITHUB_TOKEN }}
        output: ' '
    - name: Echo file changes
      run: |
        echo Changed files: ${{ steps.get_file_changes.outputs.files }}
```
**Expected behavior**
Files should output with spaces between them, e.g. `file1 file2`. Instead, they are output together: `file1file2`

**Comment by trilom** [comment]
This should be all taken care of according to tests and stuff.  Please let me know if you see differently

**Comment by dorner** [comment]
@trilom this may work in tests but I've confirmed it does *not* work in a real workflow. It looks like GitHub automatically trims all input strings when you call `getInput()`. Passing a single space string turns it into an empty string which the code then replaces with `'json'`.

**Comment by dorner** [comment]
We'd likely need some kind of sentinel value for this case e.g. the word "space" to represent an empty space.

**Comment by jpmckinney** [comment]
I arrived here from https://github.com/pre-commit/action/issues/7#issuecomment-884570441

However, I see that the `space` sentinel value was reverted in https://github.com/trilom/file-changes-action/commit/86dd487d645c37b090750d64d7061dcd5e123614

So, I assume `' '` Just Works™ now?
