### ISSUE TITLE
Pull request is showing only changes in the last commit

### ISSUE THREAD

**Issue by dorner** [trilom/file-changes-action#85]
Pretty sure this used to work, but as of now, if you have a pull request with multiple commits, it looks like the action is only pulling in the changes made in the most recent commit, even if other commits between the target and source branches made other file changes.

**Workflow**
    - name: Get file changes
      id: get_file_changes
      uses: trilom/file-changes-action@v1.2.1
      with:
        output: ','
        fileOutput: ','
    - name: Echo file changes
      run: |
        echo Changed files: ${{ steps.get_file_changes.outputs.files }}

**Expected behavior**
All files changed between the two branches should be included.

**Comment by trilom** [comment]
Ok - so allegedly I can type /integration and get an integration test.

**Comment by trilom** [comment]
This should be all wrapped up in #92

**Comment by dorner** [comment]
Confirmed that latest version works! Thanks!
